kadai2/config/routes.rb
Rails.application.routes.draw do
  resources :members
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

kadai2/app/models/member.rb
class Member < ApplicationRecord
  validates :name, presence: true, uniqueness: true, length: { minimum: 1, maximum: 20 }

  validates :height, presence: true
  validates :weight, presence: true

  validate :height_must_be_positive
  validate :weight_must_be_positive

  private

  def height_must_be_positive
    if height.present? && height < 1
      errors.add(:height, "は1以上を入力してください")
    end
  end

  def weight_must_be_positive
    if weight.present? && weight < 1
      errors.add(:weight, "は1以上を入力してください")
    end
  end
end

kadai2/app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: %i[ show edit update destroy ]

  # GET /members or /members.json
  def index
    @members = Member.all
  end

  # GET /members/1 or /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members or /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: "Member was successfully created." }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1 or /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: "Member was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1 or /members/1.json
  def destroy
    @member.destroy!

    respond_to do |format|
      format.html { redirect_to members_path, notice: "Member was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def member_params
      params.expect(member: [ :name, :height, :weight ])
    end
end

kadai2/app/helpers/members_helper.rb
module MembersHelper
end

kadai2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Kadai2" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

kadai2/app/views/members/_form.html.erb
<%= form_with(model: member) do |form| %>
  <% if member.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
        <% member.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :height, style: "display: block" %>
    <%= form.text_field :height %>
  </div>

  <div>
    <%= form.label :weight, style: "display: block" %>
    <%= form.text_field :weight %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

kadai2/app/views/members/_member.html.erb
<div id="<%= dom_id member %>">
  <p>
    <strong>Name:</strong>
    <%= member.name %>
  </p>

  <p>
    <strong>Height:</strong>
    <%= member.height %>
  </p>

  <p>
    <strong>Weight:</strong>
    <%= member.weight %>
  </p>

</div>

kadai2/app/views/members/edit.html.erb
<% content_for :title, "Editing member" %>

<h1>Editing member</h1>

<%= render "form", member: @member %>

<br>

<div>
  <%= link_to "Show this member", @member %> |
  <%= link_to "Back to members", members_path %>
</div>

kadai2/app/views/members/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Members" %>

<h1>Members</h1>

<div id="members">
  <% @members.each do |member| %>
    <%= render member %>
    <p>
      <%= link_to "Show this member", member %>
    </p>
  <% end %>
</div>

<%= link_to "New member", new_member_path %>

kadai2/app/views/members/new.html.erb
<% content_for :title, "New member" %>

<h1>New member</h1>

<%= render "form", member: @member %>

<br>

<div>
  <%= link_to "Back to members", members_path %>
</div>

kadai2/app/views/members/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @member %>

<div>
  <%= link_to "Edit this member", edit_member_path(@member) %> |
  <%= link_to "Back to members", members_path %>

  <%= button_to "Destroy this member", @member, method: :delete %>
</div>