kadai3/config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'  # トップ画面

  resources :users, only: [:new, :create, :show]  # ユーザーのサインアップ・マイページ
  resource :session, only: [:new, :create, :destroy]  # ログイン・ログアウト
end

kadai3/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

kadai3/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

kadai3/app/controllers/application_controller.rb
# app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user.present?
  end
end

kadai3/app/controllers/sessions_controller.rb
# app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # ログイン画面
  def new
  end

  # ログイン処理
  def create
    @user = User.find_by(email: params[:email])
    if @user&.authenticate(params[:password])
      session[:user_id] = @user.id  # ログイン状態にする
      redirect_to user_path(@user), notice: "ログイン成功!"
    else
      flash.now[:alert] = "ログイン失敗: メールアドレスまたはパスワードが間違っています"
      render :new
    end
  end

  # ログアウト処理
  def destroy
    session[:user_id] = nil  # ログアウト状態にする
    redirect_to root_path, notice: "ログアウトしました。"
  end
end

kadai3/app/controllers/users_controller.rb
# app/controllers/users_controller.rb
class UsersController < ApplicationController
  # サインアップ画面
  def new
    @user = User.new
  end

  # ユーザー作成（サインアップ）
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id  # ユーザーをログイン状態にする
      redirect_to user_path(@user)  # マイページにリダイレクト
    else
      render :new  # サインアップ失敗時に再度フォームを表示
    end
  end

  # マイページ画面（ログインしていないとアクセスできないように）
  def show
    @user = current_user
    redirect_to root_path unless logged_in?  # ログインしていない場合はトップにリダイレクト
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

kadai3/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

kadai3/app/helpers/application_helper.rb
module ApplicationHelper
end

kadai3/app/helpers/sessions_helper.rb
module SessionsHelper
end

kadai3/app/helpers/users_helper.rb
module UsersHelper
end

kadai3/app/helpers/welcome_helper.rb
module WelcomeHelper
end

kadai3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Kadai3" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

kadai3/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

kadai3/app/views/users/new.html.erb
<h1>サインアップ</h1>

<%= form_with model: @user, local: true do |form| %>
  <% if @user.errors.any? %>
    <div>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, "名前" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, "メールアドレス" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password, "パスワード" %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation, "パスワードの確認" %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div>
    <%= form.submit "サインアップ" %>
  </div>
<% end %>

kadai3/app/views/users/show.html.erb
<!-- app/views/users/show.html.erb -->
<h1>マイページ画面</h1>

<p>名前: <%= @user.name %></p>
<p>メールアドレス: <%= @user.email %></p>

<p>ハッシュ化されたパスワード: <%= @user.password_digest %></p>

<%= link_to 'ログアウト', session_path, method: :delete %> |
<%= link_to 'トップに戻る', root_path %>

kadai3/app/views/welcome/index.html.erb
<!-- app/views/welcome/index.html.erb -->
<h1>トップ画面</h1>

<% if logged_in? %>
  <p>こんにちは、<%= current_user.name %>さん！</p>
  <%= link_to 'マイページ', user_path(current_user) %> |
  <%= link_to 'ログアウト', session_path, method: :delete %>
<% else %>
  <%= link_to 'サインアップ', new_user_path %> |
  <%= link_to 'ログイン', new_session_path %>
<% end %>